/* ═══════════════════════════════════════════════
   SHARED CURRICULUM DATA
   Included by: courses.html, post.html, admin.html
   ═══════════════════════════════════════════════ */

const TIERS = {
  foundation: {
    label:    'Foundation',
    class:    'Class 5–8',
    color:    '#f97316',
    shadow:   'rgba(249,115,22,0.35)',
    pill:     'linear-gradient(90deg,#f97316,#fb923c)',
    original: '₹1,999',
    price:    '₹799',
    modules: [
      { icon: '🤖', title: 'What is Artificial Intelligence?',        duration: '45 min',  lessons: 5  },
      { icon: '🧠', title: 'How Does AI Think? Data & Patterns',      duration: '50 min',  lessons: 6  },
      { icon: '🌲', title: 'Machine Learning — Teaching Machines',    duration: '55 min',  lessons: 6  },
      { icon: '🇮🇳', title: 'AI in Daily Life — Indian Examples',    duration: '40 min',  lessons: 5  },
      { icon: '💬', title: 'Prompt Engineering for Kids',             duration: '50 min',  lessons: 6  },
      { icon: '🎨', title: 'Creative AI — Art, Music, Stories',       duration: '45 min',  lessons: 5  },
      { icon: '⚖️', title: 'Ethics — Responsible AI Citizen',         duration: '40 min',  lessons: 5  },
      { icon: '🏗️', title: 'PROJECT: Build a Website with AI',        duration: '90 min',  lessons: 8,  isProject: true },
    ],
  },
  explorer: {
    label:    'Explorer',
    class:    'Class 9–12',
    color:    '#16a34a',
    shadow:   'rgba(22,163,74,0.35)',
    pill:     'linear-gradient(90deg,#16a34a,#22c55e)',
    original: '₹3,499',
    price:    '₹1,499',
    modules: [
      { icon: '🐍', title: 'Python for AI — Fast Track',             duration: '90 min',  lessons: 10 },
      { icon: '📊', title: 'Machine Learning Deep Dive',             duration: '90 min',  lessons: 10 },
      { icon: '🧠', title: 'Neural Networks & Deep Learning',        duration: '85 min',  lessons: 9  },
      { icon: '💬', title: 'Natural Language Processing',            duration: '75 min',  lessons: 8  },
      { icon: '👁️', title: 'Computer Vision',                        duration: '80 min',  lessons: 9  },
      { icon: '🔧', title: 'AI Tools & APIs',                        duration: '70 min',  lessons: 8  },
      { icon: '⚖️', title: 'AI Safety & Ethics (Advanced)',          duration: '50 min',  lessons: 6  },
      { icon: '🤖', title: 'PROJECT: Build an AI Agent',             duration: '120 min', lessons: 12, isProject: true },
    ],
  },
  expert: {
    label:    'Expert',
    class:    'Graduation',
    color:    '#7c3aed',
    shadow:   'rgba(124,58,237,0.35)',
    pill:     'linear-gradient(90deg,#7c3aed,#a855f7)',
    original: '₹5,999',
    price:    '₹2,499',
    modules: [
      { icon: '⚙️', title: 'Advanced ML & MLOps',                            duration: '110 min', lessons: 12 },
      { icon: '🔥', title: 'LLMs, Transformers & Foundation Models',         duration: '100 min', lessons: 12 },
      { icon: '✍️', title: 'Claude API & Prompt Engineering Pro',            duration: '90 min',  lessons: 10 },
      { icon: '💻', title: 'Claude Code — AI-Assisted Development',          duration: '90 min',  lessons: 10 },
      { icon: '🔌', title: 'MCP — Model Context Protocol',                  duration: '80 min',  lessons: 9  },
      { icon: '☁️', title: 'Cloud AI Platforms (AWS, GCP, Azure)',           duration: '110 min', lessons: 12 },
      { icon: '🤝', title: 'AI Agents & Multi-Agent Systems',                duration: '100 min', lessons: 11 },
      { icon: '🔒', title: 'Production AI, Security & Compliance',           duration: '90 min',  lessons: 10 },
      { icon: '🏆', title: 'PROJECT: Cloud-Level AI Integration System',     duration: '180 min', lessons: 16, isProject: true },
    ],
  },
  ai_engineer: {
    label:    'AI Engineering',
    class:    'Professional',
    color:    '#0369a1',
    shadow:   'rgba(3,105,161,0.35)',
    pill:     'linear-gradient(90deg,#0369a1,#0ea5e9)',
    original: '₹8,999',
    price:    '₹3,999',
    modules: [
      { icon: '🏗️', title: 'Data Engineering Fundamentals',                  duration: '100 min', lessons: 11 },
      { icon: '🐍', title: 'Python & SQL for Data Engineering',              duration: '110 min', lessons: 12 },
      { icon: '⚡', title: 'Apache Spark & Distributed Computing',           duration: '120 min', lessons: 14 },
      { icon: '🔄', title: 'Data Pipelines & Orchestration (Airflow)',       duration: '110 min', lessons: 12 },
      { icon: '☁️', title: 'Cloud Data Platforms — BigQuery, Redshift, S3', duration: '120 min', lessons: 13 },
      { icon: '🔥', title: 'LLM Integration & Generative AI APIs',           duration: '100 min', lessons: 11 },
      { icon: '🤖', title: 'Building & Deploying AI Agents',                 duration: '110 min', lessons: 12 },
      { icon: '📡', title: 'Real-Time Streaming with Kafka',                 duration: '100 min', lessons: 11 },
      { icon: '🔒', title: 'Data Governance, Security & Compliance',         duration: '90 min',  lessons: 10 },
      { icon: '📈', title: 'Monitoring, Observability & MLOps at Scale',     duration: '100 min', lessons: 11 },
      { icon: '🚀', title: 'PROJECT: End-to-End AI Data Pipeline System',    duration: '240 min', lessons: 20, isProject: true },
    ],
  },
};
